<div class="container">
    <form action="index.php?action=login" method="POST">
        <fieldset class="panel__fieldset"><legend>Formulaire de connexion :</legend>
            <label class="panel__label" for="mail">Adresse mail :</label>
            <input class="panel__input" type="text" id="mail" name="mail"/>
            <label class="panel__label" for="password">Mot de passe :</label>
            <input class="panel__input" type="password" id="password" name="password"/>
            <button type="submit" class="form__button">Envoyer</button>
        </fieldset>
    </form>
</div>