<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Artshare</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css" integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital@0;1&family=Open+Sans:ital@0;1&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="css/style.css" type="text/css"/>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
</head>
<body>
    <header class="header">
        <div class="container">
            <div class="site__title">
                <a href="index.php">
                    <span class="header__title">Artshare</span>
                </a>
            </div>
            <nav>
                <?php if($this -> isConnect()) : ?>
                <div class="nav__bar">
                    <a href="index.php?action=userpanel" class="nav__button">Menu</a>
                    <p class="hello"> Bonjour <?=$_SESSION['user']['pseudo']?> !</p>
                    <a href="index.php?action=logout" class="nav__button">Déconnexion</a>
                </div>
                <?php else : ?>
                <div class="nav__bar">
                    <a href="index.php?action=login" class="nav__button">Connexion</a>
                    <a href="index.php?action=register" class="nav__button">Inscription</a>
                </div>
                <?php endif; ?>
            </nav>
        </div>
    </header>
    <main>
        <?php require $template.".phtml"; ?>
    </main>
    <footer class="footer">
        <div class="container">
            <p class="footer__title"><a href="#"><i class="fa-solid fa-arrow-up"></i>Artshare<i class="fa-solid fa-arrow-up"></i></a></p>
        </div>
    </footer>
    <script src="javascript/script.js"></script>
</body>
</html>